### ISSUE TITLE
Testing only in Localhost can create problem

### ISSUE THREAD

**Issue by Talismanic** [redhat-cip/dci-ansible#16]
Greetings,
I am an engineer who is interested in infrastructure as code testing. Currently, I am looking for testing anti-patterns in iac test scripts. I noticed Local-only Testing occurring in test instances. This can give happy test results in the local environment but in a real production system test can fail due to the difference in the environment. My recommendation is to test IaC code in an isolated non-local environment which needs to be similar to the production environment.

So I have the following queries:

Do you agree that this is an IaC testing anti-pattern?
Do you want to fix this?

Any feedback is appreciated.

Source Files:
https://github.com/redhat-cip/dci-ansible/blob/master/tests/scenario-tests/openstack/feeder.yml

**Comment by guillaumevincent** [comment]
Hello @Talismanic,

apparently you copy paste this issue on 16 different repos without really looking at the code right ?

My feedback: feeder.yml is not testing infrastructure. 

> My recommendation is to test IaC code in an isolated non-local environment which needs to be similar to the production environment.

Both are interesting and don't catch the same issue; One is easier to write and maintain compare to the other type of test.

I close.

Feel free to continue the discussion here

**Comment by Talismanic** [comment]
> apparently you copy paste this issue on 16 different repos without really looking at the code right ?

Not actually. In fact, I have run some script to identify common testing anti-patterns in the ansible test scripts. Now I am verifying how good the script performed. It may create false positive alarm. What I am seeing, in your case it is false-positive.

> Feel free to continue the discussion here

Thanks for giving this option. My idea is, if we use some testing tool like Molecule, we may be able to create a customized environment (with Dockers may be) which will resemble our production environment where the actual code will run. So, we can be sure that the test which are resulting positive cases will result in positive cases also when they will run in real production infra. For example, we have seen one kafka testing script resulted positive in localhost. But it failed in production as the production system did not have java/openjdk and there was no dependency task in the main production code to install java/openjdk before installing kafka. 

Does that make any sense to you?
