### ISSUE TITLE
dci_component hangs

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ansible#2]
I had the case where `dci_component` has been frozen for hours. I'm not sure what happened thus.

**Comment by dsavineau** [comment]
Maybe the api has been restarted during dci_component action ?

**Comment by goneri** [comment]
I already had the case, the download was interrupted by a restart of the server.

**Comment by goneri** [comment]
It has just happened to me. dci_component was frozen, the server has been running without any reboot for 2 days. So it's something else.

**Comment by goneri** [comment]
Fixed by the new timeout in dciclient.
